### ISSUE TITLE
Disabled field

### ISSUE THREAD

**Issue by thiagodeluca** [chronotruck/vue-ctk-time-picker#1]
Any chance to pass something like :disabled to the time field?

Tks

**Comment by LouisMazel** [comment]
Hello,

This plugin is unmaintained. You can use `vue-ctk-date-time-picker`. 
With him, you have the 'disabled' option and you can only use the time-picker 

Links : 
- [Repo](https://github.com/chronotruck/vue-ctk-date-time-picker)
- [Demo](https://htmlpreview.github.io/?https://github.com/chronotruck/vue-ctk-date-time-picker/blob/master/demo/dist/index.html)
